# Generated by Django 4.2.4 on 2023-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='', upload_to='change_surname/documents/static')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалено')], max_length=20)),
            ],
        ),
    ]
