# Generated by Django 4.2.4 on 2023-11-15 23:33

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли пользователь?')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_user_permissions', to='auth.permission', verbose_name='Права доступа')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', documents.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=100, unique=True)),
                ('document_name', models.CharField(max_length=100, unique=True)),
                ('document_overview', models.TextField(blank=True)),
                ('document_description', models.TextField(blank=True)),
                ('document_image', models.CharField(default='not_found.jpg', max_length=10000)),
                ('document_price', models.FloatField()),
                ('document_status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалено')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='NameChangeApplications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_application_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_application_acceptance', models.DateTimeField(blank=True, null=True)),
                ('date_of_application_completion', models.DateTimeField(blank=True, null=True)),
                ('new_surname', models.CharField(max_length=50)),
                ('reason_for_change', models.TextField()),
                ('application_status', models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('deleted', 'Удален')], default='created', max_length=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='documents.customuser')),
                ('moderator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to='documents.customuser')),
            ],
            options={
                'verbose_name_plural': 'NameChangeApplication',
                'db_table': 'name_change_applications',
            },
        ),
        migrations.CreateModel(
            name='DocumentsApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.namechangeapplications')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.documents')),
            ],
            options={
                'verbose_name_plural': 'DocumentsApplications',
                'db_table': 'documents_applications',
            },
        ),
        migrations.AddConstraint(
            model_name='documentsapplications',
            constraint=models.UniqueConstraint(fields=('application_id', 'document_id'), name='pk'),
        ),
    ]
