# Generated by Django 4.2.4 on 2023-10-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentsapplications',
            unique_together={('application_id', 'document_id')},
        ),
    ]
