# Generated by Django 4.2.4 on 2023-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=100)),
                ('document_overview', models.TextField(blank=True)),
                ('document_description', models.TextField(blank=True)),
                ('document_image', models.ImageField(default='', upload_to='change_surname/documents/static')),
                ('document_status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалено')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Docs',
        ),
    ]
