# Generated by Django 4.2.4 on 2023-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='otchestvo',
            field=models.CharField(default=1, max_length=150, verbose_name='Отчетсво'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='pasport',
            field=models.CharField(default=1, max_length=11, verbose_name='Паспортные данные(серия и номер)'),
            preserve_default=False,
        ),
    ]
