# Generated by Django 4.2.4 on 2023-10-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentsapplications_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='namechangeapplications',
            name='document',
            field=models.ManyToManyField(to='documents.documents'),
        ),
    ]
