# Generated by Django 4.2.4 on 2023-10-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_namechangeapplications_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namechangeapplications',
            name='document',
        ),
    ]
