# Generated by Django 4.2.4 on 2023-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_users_alter_documents_options_namechangeapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
