# Generated by Django 4.2.4 on 2023-10-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_namechangeapplications_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsapplications',
            name='document_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.documents'),
        ),
    ]
