# Generated by Django 4.2.4 on 2023-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documents_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_image',
            field=models.CharField(default='not_found.jpg', max_length=10000),
        ),
    ]
