# Generated by Django 4.2.4 on 2023-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documents_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namechangeapplication',
            name='date_of_application_acceptance',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='namechangeapplication',
            name='date_of_application_completion',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='namechangeapplication',
            name='reason_for_change',
            field=models.TextField(),
        ),
    ]
