# Generated by Django 4.2.4 on 2023-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_namechangeapplication_date_of_application_acceptance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namechangeapplication',
            name='application_status',
            field=models.CharField(auto_created='created', choices=[('created', 'Создан'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('deleted', 'Удален')], max_length=20),
        ),
        migrations.AlterField(
            model_name='namechangeapplication',
            name='date_of_application_acceptance',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='namechangeapplication',
            name='date_of_application_completion',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
