# Generated by Django 4.2.4 on 2023-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_namechangeapplication_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namechangeapplication',
            name='application_status',
            field=models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('deleted', 'Удален')], default='created', max_length=20),
        ),
    ]
