# Generated by Django 4.2.4 on 2023-10-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentsapplications_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsapplications',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.namechangeapplications'),
        ),
    ]
