# Generated by Django 4.2.4 on 2023-09-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_namechangeapplication_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namechangeapplication',
            name='date_of_application_acceptance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namechangeapplication',
            name='date_of_application_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
