# Generated by Django 4.2.4 on 2023-12-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_namechangeapplications_mfc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_status',
            field=models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалено'), ('basket', 'В корзине')], max_length=20),
        ),
    ]
