# Generated by Django 4.2.4 on 2023-10-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_documentsapplications_application_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentsApplications',
        ),
    ]
