# Generated by Django 4.2.4 on 2023-10-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_delete_documentsapplications'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.namechangeapplications')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.documents')),
            ],
            options={
                'verbose_name_plural': 'DocumentsApplications',
                'db_table': 'documents_applications',
                'unique_together': {('application_id', 'document_id')},
            },
        ),
    ]
