# Generated by Django 4.2.4 on 2023-09-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_documents_id_remove_documentsapplications_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsapplications',
            old_name='documnet_id',
            new_name='document_id',
        ),
    ]
