# Generated by Django 4.2.4 on 2023-10-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentsapplications'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentsapplications',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documentsapplications',
            constraint=models.UniqueConstraint(fields=('application_id', 'document_id'), name='unique_constraint_name'),
        ),
    ]
