# Generated by Django 4.2.4 on 2023-10-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_documentsapplications_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsapplications',
            name='application_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='documents.namechangeapplications'),
        ),
    ]
