# Generated by Django 4.2.4 on 2023-10-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0018_remove_documentsapplications_application_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=100, unique=True)),
                ('document_name', models.CharField(max_length=100, unique=True)),
                ('document_overview', models.TextField()),
                ('document_description', models.TextField()),
                ('document_image', models.CharField(max_length=100)),
                ('document_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NameChangeApplications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_application_creation', models.DateTimeField()),
                ('date_of_application_acceptance', models.DateTimeField(blank=True, null=True)),
                ('date_of_application_completion', models.DateTimeField(blank=True, null=True)),
                ('new_surname', models.CharField(max_length=50)),
                ('reason_for_change', models.TextField()),
                ('application_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'name_change_applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentsApplications',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='documents.documents')),
            ],
            options={
                'db_table': 'documents_applications',
                'managed': False,
            },
        ),
    ]
