# Generated by Django 4.2.4 on 2023-10-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_auto_20231003_2141'),
    ]

    operations = [
    ]
