# Generated by Django 4.2.4 on 2023-10-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20231003_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='documentsapplications',
            options={'verbose_name_plural': 'DocumentsApplications'},
        ),
        migrations.AlterModelOptions(
            name='namechangeapplications',
            options={'verbose_name_plural': 'NameChangeApplication'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
