# Generated by Django 4.2.4 on 2023-10-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_documents_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsapplications',
            name='application_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.namechangeapplications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentsapplications',
            name='document_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentsapplications',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namechangeapplications',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='documents.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namechangeapplications',
            name='moderator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to='documents.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_image',
            field=models.ImageField(default='change_surname/documents/static/not_found.jpeg', upload_to='change_surname/documents/static'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_status',
            field=models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалено')], max_length=20),
        ),
        migrations.AlterField(
            model_name='namechangeapplications',
            name='application_status',
            field=models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('deleted', 'Удален')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='namechangeapplications',
            name='date_of_application_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('moderator', 'Модератор')], max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='documentsapplications',
            unique_together={('application_id', 'document_id')},
        ),
        migrations.RemoveField(
            model_name='documentsapplications',
            name='document',
        ),
    ]
