# Generated by Django 4.2.4 on 2023-10-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_documentsapplications_application_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentsapplications',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documentsapplications',
            constraint=models.UniqueConstraint(fields=('application_id', 'document_id'), name='pk'),
        ),
    ]
