# Generated by Django 4.2.4 on 2023-10-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_alter_documentsapplications_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsapplications',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='documentsapplications',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='namechangeapplications',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='namechangeapplications',
            name='moderator_id',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='DocumentsApplications',
        ),
        migrations.DeleteModel(
            name='NameChangeApplications',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
