# Generated by Django 4.2.4 on 2023-10-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0025_remove_documentsapplications_application_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=100, unique=True)),
                ('document_name', models.CharField(max_length=100, unique=True)),
                ('document_overview', models.TextField(blank=True)),
                ('document_description', models.TextField(blank=True)),
                ('document_image', models.ImageField(default='change_surname/documents/static/not_found.jpeg', upload_to='change_surname/documents/static')),
                ('document_status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалено')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('moderator', 'Модератор')], max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='NameChangeApplications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_application_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_application_acceptance', models.DateTimeField(blank=True, null=True)),
                ('date_of_application_completion', models.DateTimeField(blank=True, null=True)),
                ('new_surname', models.CharField(max_length=50)),
                ('reason_for_change', models.TextField()),
                ('application_status', models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('deleted', 'Удален')], default='created', max_length=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='documents.users')),
                ('moderator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to='documents.users')),
            ],
            options={
                'verbose_name_plural': 'NameChangeApplication',
                'db_table': 'name_change_applications',
            },
        ),
        migrations.CreateModel(
            name='DocumentsApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.namechangeapplications')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.documents')),
            ],
            options={
                'verbose_name_plural': 'DocumentsApplications',
                'db_table': 'documents_applications',
            },
        ),
        migrations.AddConstraint(
            model_name='documentsapplications',
            constraint=models.UniqueConstraint(fields=('application_id', 'document_id'), name='pk'),
        ),
    ]
