# Generated by Django 4.2.4 on 2023-10-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_initial'),
    ]

    operations = [
    ]
