# Generated by Django 4.2.4 on 2023-10-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_alter_documentsapplications_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_image',
            field=models.CharField(max_length=255),
        ),
    ]
