# Generated by Django 4.2.4 on 2023-10-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_alter_documents_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_image',
            field=models.CharField(max_length=10000),
        ),
    ]
